config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'confirmations/new'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/my-account',    to: 'users#show'                # tag 1
  get    '/my-account/order-history' ,    to: 'users#edit' # tag 2
  get    '/my-account/profile' ,    to: 'orders#index'     # tag 3
  # resources :users, except: [:edit] do
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :confirmations,       only: [:new, :create]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :rooms do
    resources :messages
  end
  get '/microposts', to: 'microposts#home'
  resources :products, only: [:index, :show] do
    resources :reviews
  end
  resources :cart_items, only: [:create, :update, :destroy]
  resources :guest_cart_items, only: [:create, :update, :destroy]
  get 'cart', to: 'cart#index'
  resources :wish_items, only: [:create, :destroy]
  resources :guest_wish_items, only: [:create, :destroy]
  get 'wish', to: 'wish#index'
  resources :orders
  get 'checkout1', to: 'orders#checkout1'
  get 'checkout2', to: 'orders#checkout2'
  get 'checkout3', to: 'orders#checkout3'
  get 'checkout4', to: 'orders#checkout4'
  get 'checkout5', to: 'orders#checkout5'
  get 'addresses', to: 'addresses#index'

  namespace :admin do
    # Root API landing (optional)
    root 'static_pages#home'
    resources :users
    # Product endpoints
    resources :products do
      collection do
        get :filters
      end
    end
    resources :orders
  end

  namespace :api, format: "json" do
    root   'static_pages#home'
    resources :sessions,          only: [:index]
    delete '/logout',             to: 'sessions#destroy'
    post   '/login',              to: 'sessions#create'
    post   '/refresh',            to: 'sessions#refresh'
    post   '/revoke',             to: 'sessions#revoke'
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: [:create, :update]
    resources :password_resets,     only: [:create, :update]
    resources :microposts,          only: [:create, :destroy]
    resources :post_medias,         only: [:create, :destroy]
    resources :posts,               only: [:create, :destroy]
    resources :relationships,       only: [:create, :destroy]
    resources :products
    namespace :v1 do
      get "users", to: "users#index"
      get "products", to: "products#index"
      get "wish", to: "wish#index"
      get "cart", to: "cart#index"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  post "/graphql", to: "graphql#execute"
  post '/api/ai/chat', to: 'api/ai#chat'
end

app/views/search/index.html.erb
<form class="product_search" id="product_search" action="/search" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
  <input type="search" name="q[productname_cont]" id="q_productname_cont" />
  <input type="submit" name="commit" value="Search" data-disable-with="Search" />
</form>


<h1>Kết quả tìm kiếm cho <%= %></h1>


<table border="1">
  <tr>
    <th>id sản phẩm:</th>
    <th>Tên Sản Phẩm:</th> 
    <th>Avatar:</th>  
    <th>Images:</th>  
    <th>Giá bán:</th>
    <th>Giá gốc:</th>
    <th>Màu - color:</th>
    <th>Dòng franchise:</th>
    <th>Loại producttype:</th>
    <th>Nhãn brand:</th>
    <th>Danh mục category:</th>
    <th>Môn sport:</th>
    <th>sku:</th>
    <th>In stock:</th>
</tr>

<% @products.each do |product| %>
<tr>

    <td><%= product.id %></td>
    <td><%= product.productname %></td>
    <td>
        <% if product.stock.zero? %>
            Out of stock
    <% else %>
    <%= image_tag product.avatar, :height => "100",:width=>"100" %>
        <%= form_for product, :url => cart_items_path, :html => { :method => :post } do |f|%>
        <%= f.number_field :quantity, value: 1, class: "number-tag", min: 1 %>
      <%= f.hidden_field :product_id, value: product.id %>
      <%= f.submit 'Add to Cart', class: "btn btn-success" %>
<% end %>
<% end %>
<%= form_for product, :url => wish_items_path, :html => { :method => :post } do |f|%>
      <%= f.hidden_field :product_id, value: product.id %>
      <%= f.submit @wish.wish_items.find_by(product_id: product.id) ? 'Remove from Wish' : 'Add to Wish', class: "btn btn-success" %>    
<% end %>
    </td>
    <td>
        <% product.images.each do |image| %>
        <%= image_tag image , :height => "50",:width=>"50" %>
        <% end %> 
    </td>
    <td><%= product.price %></td>
    <td><%= product.originalpride %></td>
    <td>
        <%= product.subcolor_id && product.color_id  ? product.color.subcolors.find(product.subcolor_id).subcolor_name : '' %>
        <%= !product.subcolor_id && product.color_id  ? product.color.color_name : '' %>  
        <%= !product.subcolor_id && !product.color_id  ? '' : '' %> 
        <%= product.subcolor_id && !product.color_id  ?  'có subcolor nhưng ko có color' : '' %> 
    </td>

    <td><%= product.franchise_id ? product.franchise.franchise_name: '' %></td>
    <td><%= product.producttype_id ? product.producttype.producttype_name: '' %></td>
    <td><%= product.brand_id ? product.brand.brand_name: '' %></td>
    <td>
        <%= product.subcategory_id && product.category_id  ? product.category.subcategories.find(product.subcategory_id).subcategory_name : '' %>
        <%= !product.subcategory_id && product.category_id  ? product.category.category_name : '' %>  
        <%= !product.subcategory_id && !product.category_id  ? '' : '' %> 
        <%= product.subcategory_id && !product.category_id  ?  'có subcategory nhưng ko có category' : '' %> 
    </td>
    <td><%= product.sport_id ? product.sport.sport_name: '' %></td>
    <td><%= product.sku %></td>
    <td><%= product.stock %></td>
    <td><%= link_to 'Xem', product_path(product) %></td>
    <% if current_user.try(:admin?) %>
    <td><%= link_to 'Sửa', edit_product_path(product) %></td>
    <td><%= link_to 'Xóa', product_path(product),
    method: :delete,
    data: { confirm: 'Bạn có chắc không?' } %></td>
    <% end %>
</tr>
<% end %>
</table>

app/views/search/luutruindex.html.erb
<% provide(:title, "Search") %>
<script type="text/javascript">
  $(document).ready(function() { 
      /*--------------------------
    Newsletter Popup Js 
---------------------------- */ 
      $("#newsletter-popup-conatiner").mouseup(function(e){
        var popContainer = $("#newsletter-popup-conatiner");
        var newsLatterPop = $("#newsletter-pop-up"); 
        if(e.target.id != newsLatterPop.attr('id') && !newsLatterPop.has(e.target).length)
        {
          popContainer.fadeOut();
        }
      });
      $('.hide-popup').on("click", function(){
        var popContainer = $("#newsletter-popup-conatiner");
        $('#newsletter-popup-conatiner')
        {
          popContainer.fadeOut();
        }
      });

      $('#dont_show').on("click", function(){
        $.cookie('popup_cookie', 'pclosed', {
          expires: 3,
          path: '/'
        });
        $('.hide-popup').trigger('click');
      });
      // console.log($.cookie('popup_cookie'));

      

    });
</script>
</div>
    <div class="contentforlayout">
      






 

<!-- breadcrumb -->
<div class="bread-crumb bgwhite flex-w p-l-52 p-r-15 p-t-30 p-l-15-sm">
  <a class="s-text16" href="/" title="Back to the frontpage">
    Home<i class="fa fa-angle-right m-l-8 m-r-9" aria-hidden="true"></i>
  </a>
  

  <a class="s-text16" href=""><span>Search</span></a>
  
</div>
<!--End Breadcumb area -->


<div class="container">
  <div class="row">
    <div id="content" class="col-sm-12">
      

      
      <div class="search-header">
        <h2>Search</h2>
        <br/>
      </div>
      
    </div>
  </div>
</div>

      <!-- End Content -->  

      <!-- Quickview Product-->
<div id="quickview-wrapper">
  <!-- Modal -->
  <div class="modal fade" id="productModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="modal-product">
            <!-- Start product images -->
            <div class="product-images">
              <div class="main-image images">
                <img alt="" src="" class="img-responsive">
              </div>
            </div>
            <!-- end product images -->
            <div class="product-info">
              <h1>Sleeve High Neck Bodycon Dress </h1>
              <div class="price-box">
                <p class="price"><span class="special-price"><span class="amount">$132.00</span></span></p>
              </div>
              <a href="shop.html" class="see-all">See all features</a>
              <div class="quick-add-to-cart">
                <form class="cart" action="/cart/add" method="post" enctype="multipart/form-data" id="addToCartForm">
                  <div class="numbers-row">
                    <input type="hidden" id="id" name="id" value="" />
                    <input type="number" name="quantity" id="quantity" value="1">
                  </div>
                  <button class="single_add_to_cart_button" type="submit">Add to Cart</button>
                </form>
              </div>
              <div class="quick-desc">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam fringilla augue nec est tristique auctor. Donec non est at libero.
              </div>
              <div class="social-sharing">
                <div class="widget widget_socialsharing_widget">
                  <h3 class="widget-title-modal">Share this product</h3>
                  <ul class="social-icons">
                    <li><a target="_blank" title="Facebook" href="#" class="facebook social-icon"><i class="fa fa-facebook"></i></a></li>
                    <li><a target="_blank" title="Twitter" href="#" class="twitter social-icon"><i class="fa fa-twitter"></i></a></li>
                    <li><a target="_blank" title="Pinterest" href="#" class="pinterest social-icon"><i class="fa fa-pinterest"></i></a></li>
                    <li><a target="_blank" title="Google +" href="#" class="gplus social-icon"><i class="fa fa-google-plus"></i></a></li>
                    <li><a target="_blank" title="LinkedIn" href="#" class="linkedin social-icon"><i class="fa fa-linkedin"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
            <!-- .product-info -->
          </div>
          <!-- .modal-product -->
        </div>
        <!-- .modal-body -->
      </div>
      <!-- .modal-content -->
    </div>
    <!-- .modal-dialog -->
  </div>
  <!-- END Modal -->
</div>
<!-- End Quickview Product -->  