config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'confirmations/new'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/my-account',    to: 'users#show'                # tag 1
  get    '/my-account/order-history' ,    to: 'users#edit' # tag 2
  get    '/my-account/profile' ,    to: 'orders#index'     # tag 3
  # resources :users, except: [:edit] do
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :confirmations,       only: [:new, :create]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :rooms do
    resources :messages
  end
  get '/microposts', to: 'microposts#home'
  resources :products, only: [:index, :show] do
    resources :reviews
  end
  resources :cart_items, only: [:create, :update, :destroy]
  resources :guest_cart_items, only: [:create, :update, :destroy]
  get 'cart', to: 'cart#index'
  resources :wish_items, only: [:create, :destroy]
  resources :guest_wish_items, only: [:create, :destroy]
  get 'wish', to: 'wish#index'
  resources :orders
  get 'checkout1', to: 'orders#checkout1'
  get 'checkout2', to: 'orders#checkout2'
  get 'checkout3', to: 'orders#checkout3'
  get 'checkout4', to: 'orders#checkout4'
  get 'checkout5', to: 'orders#checkout5'
  get 'addresses', to: 'addresses#index'

  namespace :admin do
    # Root API landing (optional)
    root 'static_pages#home'
    resources :users
    # Product endpoints
    resources :products do
      collection do
        get :filters
      end
    end
    resources :orders
  end

  namespace :api, format: "json" do
    root   'static_pages#home'
    resources :sessions,          only: [:index]
    delete '/logout',             to: 'sessions#destroy'
    post   '/login',              to: 'sessions#create'
    post   '/refresh',            to: 'sessions#refresh'
    post   '/revoke',             to: 'sessions#revoke'
    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :account_activations, only: [:create, :update]
    resources :password_resets,     only: [:create, :update]
    resources :microposts,          only: [:create, :destroy]
    resources :post_medias,         only: [:create, :destroy]
    resources :posts,               only: [:create, :destroy]
    resources :relationships,       only: [:create, :destroy]
    resources :products
    namespace :v1 do
      get "users", to: "users#index"
      get "products", to: "products#index"
      get "wish", to: "wish#index"
      get "cart", to: "cart#index"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  post "/graphql", to: "graphql#execute"
  post '/api/ai/chat', to: 'api/ai#chat'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  # accepts_nested_attributes_for :order_items,
  #                               allow_destroy: true

  # enum status: { unfinished: 0, finished: 1 }
  # validates :order_number, presence: true

  def list
    order_items
  end

  def total_item
    total_item = 0
    self.order_items.each do |order_item|
      total_item += order_item.quantity.to_i
    end
    total_item
  end

  def total_originalvalue
    order_items.inject(0.0) { |sum, l| sum + l.variant.originalprice * l.quantity }
  end

  def total_value
    order_items.inject(0.0) { |sum, l| sum + l.variant.price * l.quantity }
  end

  def sale
    self.total_value - self.total_originalvalue
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  layout "admin"
  def index
    @orders = Order.order(:id).page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
  end

  def checkout1
  end

  def checkout2
  end

  def checkout3
  end

  def checkout4
    @order = Order.new
  end

  def checkout5
  end

  def addresses
  end

  def create
    # Generate order_items for a subset of vatiants (products) in current_cart (current_order).

    unless current_cart.list.blank? || current_user.blank?
      order = current_user.orders.create

      current_cart.list.each { |cart_item|
        order.order_items.create!(quantity: cart_item.quantity,
                                  order_id: order.id,product_id: cart_item.product_id ,variant_id: cart_item.variant_id)
      }

      if order.save
        redirect_to checkout5_path
      else
        redirect_to request.referrer
      end
    end

    # @product = Product.find(params[:product_id])
    # @variant = Variant.find(params[:variant_id])
    # current_cart.cart(@product, @variant, params[:cart_item][:quantity], params[:cart_item][:action])
    # respond_to do |format|
    #   format.html { redirect_to request.referrer }
    #   format.turbo_stream
    # end


    # def cart(product, variant, quantity, action)
    #   if current_item = cart_items.find_by(variant: variant)
    #     current_item.quantity ||= 1
    #     action == 'edit' ? current_item.quantity = quantity.to_i : current_item.quantity += quantity.to_i
    #     current_item.save
    #   else
    #     cart_items.create(product: product,variant: variant, cart: self, quantity: quantity)
    #   end
    # end



    # @order = Order.new(order_params)

    # if @order.save
    #   redirect_to orders_path
    # else
    #   redirect_to request.referrer
    # end
  end

  def update
    @order = Order.find(params[:id])

    if @order.update(order_params)
      redirect_to admin_orders_path
    else
      render 'edit'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    redirect_to request.referrer
  end

  private
  def order_params
    params.require(:order).permit(:user_id, :address, :phone, :method, :status, :details)
  end
  def cart_params
    params.require(:cart).permit(:quantity, :cart_id, :product_id, :product_id, :variant_id)
  end
  def filtering_params(params)
    params.slice(:status, :location, :starts_with)
  end
end

app/controllers/api/orders_controller.rb
class Api::Api::OrdersController < Api::ApiController
  before_action :authenticate!

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
  end

  def checkout1
  end

  def checkout2
  end

  def checkout3
  end

  def checkout4
    @order = Order.new
  end

  def checkout5
  end

  def addresses
  end

  def create
    # Generate order_items for a subset of vatiants (products) in current_cart (current_order).

    unless current_cart.list.blank? || current_user.blank?
      order = current_user.orders.create

      current_cart.list.each { |cart_item|
        order.order_items.create!(quantity: cart_item.quantity,
                                  order_id: order.id,product_id: cart_item.product_id ,variant_id: cart_item.variant_id)
      }

      if order.save
        redirect_to checkout5_path
      else
        redirect_to request.referrer
      end
    end

    # @product = Product.find(params[:product_id])
    # @variant = Variant.find(params[:variant_id])
    # current_cart.cart(@product, @variant, params[:cart_item][:quantity], params[:cart_item][:action])
    # respond_to do |format|
    #   format.html { redirect_to request.referrer }
    #   format.turbo_stream
    # end


    # def cart(product, variant, quantity, action)
    #   if current_item = cart_items.find_by(variant: variant)
    #     current_item.quantity ||= 1
    #     action == 'edit' ? current_item.quantity = quantity.to_i : current_item.quantity += quantity.to_i
    #     current_item.save
    #   else
    #     cart_items.create(product: product,variant: variant, cart: self, quantity: quantity)
    #   end
    # end



    # @order = Order.new(order_params)

    # if @order.save
    #   redirect_to orders_path
    # else
    #   redirect_to request.referrer
    # end
  end

  def update
    @order = Order.find(params[:id])

    if @order.update(order_params)
      redirect_to admin_orders_path
    else
      render 'edit'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    redirect_to request.referrer
  end

  private
  def order_params
    params.require(:order).permit(:user_id, :address, :phone, :method, :status, :details)
  end
  def cart_params
    params.require(:cart).permit(:quantity, :cart_id, :product_id, :product_id, :variant_id)
  end
  def filtering_params(params)
    params.slice(:status, :location, :starts_with)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def edit
    @order = Order.find(params[:id])
  end

  def checkout1
  end

  def checkout2
  end

  def checkout3
  end

  def checkout4
    @order = Order.new
  end

  def checkout5
  end

  def addresses
  end

  def create
    # Generate order_items for a subset of vatiants (products) in current_cart (current_order).

    unless current_cart.list.blank? || current_user.blank?
      order = current_user.orders.create

      current_cart.list.each { |cart_item|
        order.order_items.create!(quantity: cart_item.quantity,
                                  order_id: order.id,product_id: cart_item.product_id ,variant_id: cart_item.variant_id)
      }

      if order.save
        redirect_to checkout5_path
      else
        redirect_to request.referrer
      end
    end

    # @product = Product.find(params[:product_id])
    # @variant = Variant.find(params[:variant_id])
    # current_cart.cart(@product, @variant, params[:cart_item][:quantity], params[:cart_item][:action])
    # respond_to do |format|
    #   format.html { redirect_to request.referrer }
    #   format.turbo_stream
    # end


    # def cart(product, variant, quantity, action)
    #   if current_item = cart_items.find_by(variant: variant)
    #     current_item.quantity ||= 1
    #     action == 'edit' ? current_item.quantity = quantity.to_i : current_item.quantity += quantity.to_i
    #     current_item.save
    #   else
    #     cart_items.create(product: product,variant: variant, cart: self, quantity: quantity)
    #   end
    # end



    # @order = Order.new(order_params)

    # if @order.save
    #   redirect_to orders_path
    # else
    #   redirect_to request.referrer
    # end
  end

  def update
    @order = Order.find(params[:id])

    if @order.update(order_params)
      redirect_to admin_orders_path
    else
      render 'edit'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    redirect_to request.referrer
  end

  private
  def order_params
    params.require(:order).permit(:user_id, :address, :phone, :method, :status, :details)
  end
  def cart_params
    params.require(:cart).permit(:quantity, :cart_id, :product_id, :product_id, :variant_id)
  end
  def filtering_params(params)
    params.slice(:status, :location, :starts_with)
  end
end

app/views/admin/orders/_order.html.erb
<tr>
  <th># <%= order.id %></th>
  <td><%= order.created_at %></td>
  <td><%= number_to_currency(order.total_value+5.04) %></td>
  <td><span class="badge badge-info">Being prepared</span></td>
  <!-- <td><span class="badge badge-warning">Action needed</span></td>
  <td><span class="badge badge-success">Received</span></td>
  <td><span class="badge badge-danger">Cancelled</span></td> -->
  <td>
    <a href="<%= "/#{locale.to_s}/orders/1" %>" ></a>
    <%= link_to 'View', admin_order_path(order) %>
  </td>
  <td>
    <%= link_to 'Delete', admin_order_path(order),
            remote: true,
            method: :delete,
            data: { confirm: 'You sure?' },
            class: "order-#{order.id}" %>
  </td>
</tr>

app/views/admin/orders/index.html.erb
<h1>Listing orders</h1>
<%= link_to 'New order', new_admin_order_path %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Order</th>
      <th scope="col">Date</th>
      <th scope="col">Total</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
    <%= render current_user.orders %>
</table>
<br>
<%= link_to 'Back', admin_root_path %>

app/views/admin/orders/show.html.erb
<%= link_to 'Edit', edit_admin_order_path(@order) %> |
<%= link_to 'Back', admin_orders_path %>

<!-- Hero Section-->
    <section class="padding-small">
      <div class="container">
        <div class="row">
          <!-- Customer Sidebar-->
          <%= render 'users/sidebar' %>
          <div class="col-lg-8 col-xl-9 pl-lg-3">
            <div class="basket basket-customer-order">
              <div class="basket-holder">
                <div class="basket-header">
                  <div class="row">
                    <div class="col-6">Product</div>
                    <div class="col-2">Price</div>
                    <div class="col-2">Quantity</div>
                    <div class="col-2 text-right">Total</div>
                  </div>
                </div>
                <div class="basket-body">
                  <%= render @order.order_items %>
                </div>
                <div class="basket-footer">
                  <div class="item">
                    <div class="row">
                      <div class="offset-md-6 col-4"> <strong>ORIGINAL PRICE</strong></div>
                      <div class="col-2 text-right"><strong><%= number_to_currency(@order.total_originalvalue) %></strong></div>
                    </div>
                  </div>
                  <div class="item">
                    <div class="row">
                      <div class="offset-md-6 col-4"> <strong>SALE</strong></div>
                      <div class="col-2 text-right"><strong><%= number_to_currency(@order.sale) %></strong></div>
                    </div>
                  </div>
                  <div class="item">
                    <div class="row">
                      <div class="offset-md-6 col-4"> <strong>DELIVERY</strong></div>
                      <div class="col-2 text-right"><strong>FREE</strong></div>
                    </div>
                  </div>
                  <div class="item">
                    <div class="row">
                      <div class="offset-md-6 col-4"> <strong>SALES TAX*</strong></div>
                      <div class="col-2 text-right"><strong>$5.04</strong></div>
                    </div>
                  </div>
                  <div class="item">
                    <div class="row">
                      <div class="offset-md-6 col-4"> <strong>TOTAL</strong></div>
                      <div class="col-2 text-right"><strong><%= number_to_currency(@order.total_value+5.04) %></strong></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>